# Given: A DNA string t having length at most 1000 nt.
# Return: The transcribed RNA string of t.
def main():
    example_data = "CTCCCCCTTCTCACTGGCGTTGGATCTTCCTGATCGGTGGTCGGATCAAGGCGACTCACATTTTAATGCATGCGGCC" \
                   "GGGGACCATCGTTTGGACAAGATAGCCCCAGTTGGACCTCCTGTTCTATGCGCCATGGCCTATGCTAGCGTCTTCGA" \
                   "TTTTAAGGCCGCTCCTCGTGATGCCTAGCTTGGAGAAAGCCTCCTGATTCAGGGATGAGCCCGTCATACAAAAGGAA" \
                   "ATTAGAATGCGCCTTTCTTTAAAGCTCAAATTTCCCACATAGAACGTTTGTATTAGCGTAGCGTCACCGGCCTTCAA" \
                   "ATGTCGAGATCTCTTTTGCACCAGCCATATGTATGAGCGCTTGCATTGTCTATGTTTCCTTGTTTCAAGCTAATGTC" \
                   "GGGGATGAAAGGAGGATCTCCAACCCTCGGATGTTGGCGGCTGCTGGAACCATCGGCGAGTATTTCCCTCTAGATCT" \
                   "TAACGTGCCGCCTAATGCGTGATTTCAAATACTGGCCGTAACCCCTCCAGTGAGGTTGTATACCTCTCCAGGCACTA" \
                   "AGTATGCTGAAAAGTGAGTTGAACGGCAGACCGGAGCAACCGATCGGGGTTTTGTACTTTCGTATGATTCCACGATA" \
                   "ACCGAACAAGGTCTCGTACCCTCCTTAAGCTGCTTACAGCTAGTTCAACCAGATCGAACGTCCCTATTGGCTTCGGG" \
                   "TATTATGTACGCCCCCGGCAGTGAACGATGGCTAGGTCGCGCAAGCTGGGAATTAAAATTCGGTCCATTCTCAAGCG" \
                   "GCCACACTGGGGCATGTGTCCCGAAACCGTACCTACCAGTCCCTATTTCCAGATACATCTAACCAACGCCATGCTCA" \
                   "TCCAAGAACAAAACCGTGCGGCTATCAATCGGATTAAGGATGTGATCGTTGTCCCCAG"
    example_data = example_data.replace("T", "U")
    print(example_data)

if __name__ == '__main__':
    main()